/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package associations;

public class Customer {

  // Add instance varables
    private String FirstName;
    private String LastName;
    private String StreetAddress;
    private String ZipCode;
    private Account UserAccount;

  //    A constructor that initializes the last name, first name, address, and zip code.
    public Customer(String FirstName,String LastName, String StreetAddress, String ZipCode) {
        this.FirstName = FirstName;
        this.LastName = LastName;
        this.StreetAddress = StreetAddress;
        this.ZipCode = ZipCode;
    }
  //    getLastName() - Returns a String that is the customer’s last name
    public String getLastName() {
        return LastName;
    }
  //    getFirstName() - Returns a String that is the customer’s first name
    public String getFirstName() {
        return FirstName;
    }
  //    getStreetAddress() - Returns a String indicating the customer’s street address
    public String getStreetAddress(){
        return StreetAddress;
    }
  //    getZipCode() - Returns a String indicating the customer’s zip code
    public String getZipCode(){
        return ZipCode;
    }
  //    setAccount(Account a) - Sets the Account for this customer
    public void setAccount(Account a){
        UserAccount = a;

    }
  //    getAccount() - Returns a reference to the Account object associated with this customer
    public Account getAccount(){
        return UserAccount;
    }

}
