/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package associations;

import associations.Account;
import associations.Customer;
import associations.Product;

public class Main {
    public static void main(String[] args) {


        // Instatiate objects to test your code
        Customer Mike = new Customer("Michael", "Swanson", "Seneca Hall", "13126");
        Account MikeAccount = new Account("123456", Mike);
        Product Box = new Product("Box", "37", 5.00);
        System.out.println(Mike.getFirstName());
        System.out.println(MikeAccount.getCustomer());
    }
}
